name: GitHub Pages
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.97.3
          extended: true

      - name: Build
        run: hugo --minify --gc --enableGitInfo

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        permissions:
          id-token: write
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
